# Generated by Django 3.2.13 on 2022-05-31 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('country', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('average_temperature', models.FloatField()),
                ('average_humidity', models.FloatField()),
                ('average_wind_speed', models.FloatField()),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['sensor_id'],
            },
        ),
    ]
