# Generated by Django 3.2.13 on 2022-05-31 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sensors',
            new_name='Sensor',
        ),
    ]
